// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biyunLevel.proto

#ifndef PROTOBUF_biyunLevel_2eproto__INCLUDED
#define PROTOBUF_biyunLevel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_biyunLevel_2eproto();
void protobuf_AssignDesc_biyunLevel_2eproto();
void protobuf_ShutdownFile_biyunLevel_2eproto();

class biyunLevel;

// ===================================================================

class biyunLevel : public ::google::protobuf::Message {
 public:
  biyunLevel();
  virtual ~biyunLevel();

  biyunLevel(const biyunLevel& from);

  inline biyunLevel& operator=(const biyunLevel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const biyunLevel& default_instance();

  void Swap(biyunLevel* other);

  // implements Message ----------------------------------------------

  biyunLevel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const biyunLevel& from);
  void MergeFrom(const biyunLevel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 level = 1;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 1;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // optional uint32 star1 = 2;
  inline bool has_star1() const;
  inline void clear_star1();
  static const int kStar1FieldNumber = 2;
  inline ::google::protobuf::uint32 star1() const;
  inline void set_star1(::google::protobuf::uint32 value);

  // optional uint32 star2 = 3;
  inline bool has_star2() const;
  inline void clear_star2();
  static const int kStar2FieldNumber = 3;
  inline ::google::protobuf::uint32 star2() const;
  inline void set_star2(::google::protobuf::uint32 value);

  // optional uint32 star3 = 4;
  inline bool has_star3() const;
  inline void clear_star3();
  static const int kStar3FieldNumber = 4;
  inline ::google::protobuf::uint32 star3() const;
  inline void set_star3(::google::protobuf::uint32 value);

  // optional uint32 star4 = 5;
  inline bool has_star4() const;
  inline void clear_star4();
  static const int kStar4FieldNumber = 5;
  inline ::google::protobuf::uint32 star4() const;
  inline void set_star4(::google::protobuf::uint32 value);

  // optional uint32 star5 = 6;
  inline bool has_star5() const;
  inline void clear_star5();
  static const int kStar5FieldNumber = 6;
  inline ::google::protobuf::uint32 star5() const;
  inline void set_star5(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:biyunLevel)
 private:
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_star1();
  inline void clear_has_star1();
  inline void set_has_star2();
  inline void clear_has_star2();
  inline void set_has_star3();
  inline void clear_has_star3();
  inline void set_has_star4();
  inline void clear_has_star4();
  inline void set_has_star5();
  inline void clear_has_star5();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 star1_;
  ::google::protobuf::uint32 star2_;
  ::google::protobuf::uint32 star3_;
  ::google::protobuf::uint32 star4_;
  ::google::protobuf::uint32 star5_;
  friend void  protobuf_AddDesc_biyunLevel_2eproto();
  friend void protobuf_AssignDesc_biyunLevel_2eproto();
  friend void protobuf_ShutdownFile_biyunLevel_2eproto();

  void InitAsDefaultInstance();
  static biyunLevel* default_instance_;
};
// ===================================================================


// ===================================================================

// biyunLevel

// optional uint32 level = 1;
inline bool biyunLevel::has_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void biyunLevel::set_has_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void biyunLevel::clear_has_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void biyunLevel::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 biyunLevel::level() const {
  // @@protoc_insertion_point(field_get:biyunLevel.level)
  return level_;
}
inline void biyunLevel::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.level)
}

// optional uint32 star1 = 2;
inline bool biyunLevel::has_star1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void biyunLevel::set_has_star1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void biyunLevel::clear_has_star1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void biyunLevel::clear_star1() {
  star1_ = 0u;
  clear_has_star1();
}
inline ::google::protobuf::uint32 biyunLevel::star1() const {
  // @@protoc_insertion_point(field_get:biyunLevel.star1)
  return star1_;
}
inline void biyunLevel::set_star1(::google::protobuf::uint32 value) {
  set_has_star1();
  star1_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.star1)
}

// optional uint32 star2 = 3;
inline bool biyunLevel::has_star2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void biyunLevel::set_has_star2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void biyunLevel::clear_has_star2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void biyunLevel::clear_star2() {
  star2_ = 0u;
  clear_has_star2();
}
inline ::google::protobuf::uint32 biyunLevel::star2() const {
  // @@protoc_insertion_point(field_get:biyunLevel.star2)
  return star2_;
}
inline void biyunLevel::set_star2(::google::protobuf::uint32 value) {
  set_has_star2();
  star2_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.star2)
}

// optional uint32 star3 = 4;
inline bool biyunLevel::has_star3() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void biyunLevel::set_has_star3() {
  _has_bits_[0] |= 0x00000008u;
}
inline void biyunLevel::clear_has_star3() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void biyunLevel::clear_star3() {
  star3_ = 0u;
  clear_has_star3();
}
inline ::google::protobuf::uint32 biyunLevel::star3() const {
  // @@protoc_insertion_point(field_get:biyunLevel.star3)
  return star3_;
}
inline void biyunLevel::set_star3(::google::protobuf::uint32 value) {
  set_has_star3();
  star3_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.star3)
}

// optional uint32 star4 = 5;
inline bool biyunLevel::has_star4() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void biyunLevel::set_has_star4() {
  _has_bits_[0] |= 0x00000010u;
}
inline void biyunLevel::clear_has_star4() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void biyunLevel::clear_star4() {
  star4_ = 0u;
  clear_has_star4();
}
inline ::google::protobuf::uint32 biyunLevel::star4() const {
  // @@protoc_insertion_point(field_get:biyunLevel.star4)
  return star4_;
}
inline void biyunLevel::set_star4(::google::protobuf::uint32 value) {
  set_has_star4();
  star4_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.star4)
}

// optional uint32 star5 = 6;
inline bool biyunLevel::has_star5() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void biyunLevel::set_has_star5() {
  _has_bits_[0] |= 0x00000020u;
}
inline void biyunLevel::clear_has_star5() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void biyunLevel::clear_star5() {
  star5_ = 0u;
  clear_has_star5();
}
inline ::google::protobuf::uint32 biyunLevel::star5() const {
  // @@protoc_insertion_point(field_get:biyunLevel.star5)
  return star5_;
}
inline void biyunLevel::set_star5(::google::protobuf::uint32 value) {
  set_has_star5();
  star5_ = value;
  // @@protoc_insertion_point(field_set:biyunLevel.star5)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_biyunLevel_2eproto__INCLUDED
