// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BiyunLevel.proto

#ifndef PROTOBUF_BiyunLevel_2eproto__INCLUDED
#define PROTOBUF_BiyunLevel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BiyunLevel_2eproto();
void protobuf_AssignDesc_BiyunLevel_2eproto();
void protobuf_ShutdownFile_BiyunLevel_2eproto();

class Sheet1;

// ===================================================================

class Sheet1 : public ::google::protobuf::Message {
 public:
  Sheet1();
  virtual ~Sheet1();

  Sheet1(const Sheet1& from);

  inline Sheet1& operator=(const Sheet1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sheet1& default_instance();

  void Swap(Sheet1* other);

  // implements Message ----------------------------------------------

  Sheet1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sheet1& from);
  void MergeFrom(const Sheet1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 level = 1;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 1;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // optional uint32 star1 = 2;
  inline bool has_star1() const;
  inline void clear_star1();
  static const int kStar1FieldNumber = 2;
  inline ::google::protobuf::uint32 star1() const;
  inline void set_star1(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Sheet1)
 private:
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_star1();
  inline void clear_has_star1();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 star1_;
  friend void  protobuf_AddDesc_BiyunLevel_2eproto();
  friend void protobuf_AssignDesc_BiyunLevel_2eproto();
  friend void protobuf_ShutdownFile_BiyunLevel_2eproto();

  void InitAsDefaultInstance();
  static Sheet1* default_instance_;
};
// ===================================================================


// ===================================================================

// Sheet1

// optional uint32 level = 1;
inline bool Sheet1::has_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sheet1::set_has_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sheet1::clear_has_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sheet1::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 Sheet1::level() const {
  // @@protoc_insertion_point(field_get:Sheet1.level)
  return level_;
}
inline void Sheet1::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:Sheet1.level)
}

// optional uint32 star1 = 2;
inline bool Sheet1::has_star1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Sheet1::set_has_star1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Sheet1::clear_has_star1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Sheet1::clear_star1() {
  star1_ = 0u;
  clear_has_star1();
}
inline ::google::protobuf::uint32 Sheet1::star1() const {
  // @@protoc_insertion_point(field_get:Sheet1.star1)
  return star1_;
}
inline void Sheet1::set_star1(::google::protobuf::uint32 value) {
  set_has_star1();
  star1_ = value;
  // @@protoc_insertion_point(field_set:Sheet1.star1)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BiyunLevel_2eproto__INCLUDED
