// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "BiyunLevel.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_config_2eproto();
void protobuf_AssignDesc_config_2eproto();
void protobuf_ShutdownFile_config_2eproto();

class ExcelConfig;

// ===================================================================

class ExcelConfig : public ::google::protobuf::Message {
 public:
  ExcelConfig();
  virtual ~ExcelConfig();

  ExcelConfig(const ExcelConfig& from);

  inline ExcelConfig& operator=(const ExcelConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExcelConfig& default_instance();

  void Swap(ExcelConfig* other);

  // implements Message ----------------------------------------------

  ExcelConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExcelConfig& from);
  void MergeFrom(const ExcelConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Sheet1 Sheet1s = 1;
  inline int sheet1s_size() const;
  inline void clear_sheet1s();
  static const int kSheet1SFieldNumber = 1;
  inline const ::Sheet1& sheet1s(int index) const;
  inline ::Sheet1* mutable_sheet1s(int index);
  inline ::Sheet1* add_sheet1s();
  inline const ::google::protobuf::RepeatedPtrField< ::Sheet1 >&
      sheet1s() const;
  inline ::google::protobuf::RepeatedPtrField< ::Sheet1 >*
      mutable_sheet1s();

  // @@protoc_insertion_point(class_scope:ExcelConfig)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Sheet1 > sheet1s_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();

  void InitAsDefaultInstance();
  static ExcelConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// ExcelConfig

// repeated .Sheet1 Sheet1s = 1;
inline int ExcelConfig::sheet1s_size() const {
  return sheet1s_.size();
}
inline void ExcelConfig::clear_sheet1s() {
  sheet1s_.Clear();
}
inline const ::Sheet1& ExcelConfig::sheet1s(int index) const {
  // @@protoc_insertion_point(field_get:ExcelConfig.Sheet1s)
  return sheet1s_.Get(index);
}
inline ::Sheet1* ExcelConfig::mutable_sheet1s(int index) {
  // @@protoc_insertion_point(field_mutable:ExcelConfig.Sheet1s)
  return sheet1s_.Mutable(index);
}
inline ::Sheet1* ExcelConfig::add_sheet1s() {
  // @@protoc_insertion_point(field_add:ExcelConfig.Sheet1s)
  return sheet1s_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Sheet1 >&
ExcelConfig::sheet1s() const {
  // @@protoc_insertion_point(field_list:ExcelConfig.Sheet1s)
  return sheet1s_;
}
inline ::google::protobuf::RepeatedPtrField< ::Sheet1 >*
ExcelConfig::mutable_sheet1s() {
  // @@protoc_insertion_point(field_mutable_list:ExcelConfig.Sheet1s)
  return &sheet1s_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
