# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BiyunLevel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BiyunLevel.proto',
  package='',
  serialized_pb=_b('\n\x10\x42iyunLevel.proto\"&\n\x06Sheet1\x12\r\n\x05level\x18\x01 \x01(\r\x12\r\n\x05star1\x18\x02 \x01(\rB\x11\n\x0fwang.gnim.excel')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SHEET1 = _descriptor.Descriptor(
  name='Sheet1',
  full_name='Sheet1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='Sheet1.level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='star1', full_name='Sheet1.star1', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Sheet1'] = _SHEET1

Sheet1 = _reflection.GeneratedProtocolMessageType('Sheet1', (_message.Message,), dict(
  DESCRIPTOR = _SHEET1,
  __module__ = 'BiyunLevel_pb2'
  # @@protoc_insertion_point(class_scope:Sheet1)
  ))
_sym_db.RegisterMessage(Sheet1)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017wang.gnim.excel'))
# @@protoc_insertion_point(module_scope)
