# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BiyunLevel_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x1a\x10\x42iyunLevel.proto\"\'\n\x0b\x45xcelConfig\x12\x18\n\x07Sheet1s\x18\x01 \x03(\x0b\x32\x07.Sheet1B\x11\n\x0fwang.gnim.excel')
  ,
  dependencies=[BiyunLevel_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXCELCONFIG = _descriptor.Descriptor(
  name='ExcelConfig',
  full_name='ExcelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sheet1s', full_name='ExcelConfig.Sheet1s', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=73,
)

_EXCELCONFIG.fields_by_name['Sheet1s'].message_type = BiyunLevel_pb2._SHEET1
DESCRIPTOR.message_types_by_name['ExcelConfig'] = _EXCELCONFIG

ExcelConfig = _reflection.GeneratedProtocolMessageType('ExcelConfig', (_message.Message,), dict(
  DESCRIPTOR = _EXCELCONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:ExcelConfig)
  ))
_sym_db.RegisterMessage(ExcelConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017wang.gnim.excel'))
# @@protoc_insertion_point(module_scope)
