// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: biyunLevel.proto

package wang.gnim.excel;

public final class BiyunLevel {
  private BiyunLevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface biyunLevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:biyunLevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional uint32 level = 1;</code>
     */
    int getLevel();

    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    boolean hasStar1();
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    int getStar1();

    /**
     * <code>optional uint32 star2 = 3;</code>
     */
    boolean hasStar2();
    /**
     * <code>optional uint32 star2 = 3;</code>
     */
    int getStar2();

    /**
     * <code>optional uint32 star3 = 4;</code>
     */
    boolean hasStar3();
    /**
     * <code>optional uint32 star3 = 4;</code>
     */
    int getStar3();

    /**
     * <code>optional uint32 star4 = 5;</code>
     */
    boolean hasStar4();
    /**
     * <code>optional uint32 star4 = 5;</code>
     */
    int getStar4();

    /**
     * <code>optional uint32 star5 = 6;</code>
     */
    boolean hasStar5();
    /**
     * <code>optional uint32 star5 = 6;</code>
     */
    int getStar5();
  }
  /**
   * Protobuf type {@code biyunLevel}
   */
  public static final class biyunLevel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:biyunLevel)
      biyunLevelOrBuilder {
    // Use biyunLevel.newBuilder() to construct.
    private biyunLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private biyunLevel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final biyunLevel defaultInstance;
    public static biyunLevel getDefaultInstance() {
      return defaultInstance;
    }

    public biyunLevel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private biyunLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              star1_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              star2_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              star3_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              star4_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              star5_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wang.gnim.excel.BiyunLevel.internal_static_biyunLevel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wang.gnim.excel.BiyunLevel.internal_static_biyunLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wang.gnim.excel.BiyunLevel.biyunLevel.class, wang.gnim.excel.BiyunLevel.biyunLevel.Builder.class);
    }

    public static com.google.protobuf.Parser<biyunLevel> PARSER =
        new com.google.protobuf.AbstractParser<biyunLevel>() {
      public biyunLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new biyunLevel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<biyunLevel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>optional uint32 level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int STAR1_FIELD_NUMBER = 2;
    private int star1_;
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    public boolean hasStar1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    public int getStar1() {
      return star1_;
    }

    public static final int STAR2_FIELD_NUMBER = 3;
    private int star2_;
    /**
     * <code>optional uint32 star2 = 3;</code>
     */
    public boolean hasStar2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 star2 = 3;</code>
     */
    public int getStar2() {
      return star2_;
    }

    public static final int STAR3_FIELD_NUMBER = 4;
    private int star3_;
    /**
     * <code>optional uint32 star3 = 4;</code>
     */
    public boolean hasStar3() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 star3 = 4;</code>
     */
    public int getStar3() {
      return star3_;
    }

    public static final int STAR4_FIELD_NUMBER = 5;
    private int star4_;
    /**
     * <code>optional uint32 star4 = 5;</code>
     */
    public boolean hasStar4() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 star4 = 5;</code>
     */
    public int getStar4() {
      return star4_;
    }

    public static final int STAR5_FIELD_NUMBER = 6;
    private int star5_;
    /**
     * <code>optional uint32 star5 = 6;</code>
     */
    public boolean hasStar5() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 star5 = 6;</code>
     */
    public int getStar5() {
      return star5_;
    }

    private void initFields() {
      level_ = 0;
      star1_ = 0;
      star2_ = 0;
      star3_ = 0;
      star4_ = 0;
      star5_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, star1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, star2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, star3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, star4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, star5_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, star1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, star2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, star3_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, star4_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, star5_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.biyunLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wang.gnim.excel.BiyunLevel.biyunLevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code biyunLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:biyunLevel)
        wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wang.gnim.excel.BiyunLevel.internal_static_biyunLevel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wang.gnim.excel.BiyunLevel.internal_static_biyunLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wang.gnim.excel.BiyunLevel.biyunLevel.class, wang.gnim.excel.BiyunLevel.biyunLevel.Builder.class);
      }

      // Construct using wang.gnim.excel.BiyunLevel.biyunLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        star1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        star2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        star3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        star4_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        star5_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wang.gnim.excel.BiyunLevel.internal_static_biyunLevel_descriptor;
      }

      public wang.gnim.excel.BiyunLevel.biyunLevel getDefaultInstanceForType() {
        return wang.gnim.excel.BiyunLevel.biyunLevel.getDefaultInstance();
      }

      public wang.gnim.excel.BiyunLevel.biyunLevel build() {
        wang.gnim.excel.BiyunLevel.biyunLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wang.gnim.excel.BiyunLevel.biyunLevel buildPartial() {
        wang.gnim.excel.BiyunLevel.biyunLevel result = new wang.gnim.excel.BiyunLevel.biyunLevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.star1_ = star1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.star2_ = star2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.star3_ = star3_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.star4_ = star4_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.star5_ = star5_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wang.gnim.excel.BiyunLevel.biyunLevel) {
          return mergeFrom((wang.gnim.excel.BiyunLevel.biyunLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wang.gnim.excel.BiyunLevel.biyunLevel other) {
        if (other == wang.gnim.excel.BiyunLevel.biyunLevel.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasStar1()) {
          setStar1(other.getStar1());
        }
        if (other.hasStar2()) {
          setStar2(other.getStar2());
        }
        if (other.hasStar3()) {
          setStar3(other.getStar3());
        }
        if (other.hasStar4()) {
          setStar4(other.getStar4());
        }
        if (other.hasStar5()) {
          setStar5(other.getStar5());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wang.gnim.excel.BiyunLevel.biyunLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wang.gnim.excel.BiyunLevel.biyunLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int level_ ;
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      private int star1_ ;
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public boolean hasStar1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public int getStar1() {
        return star1_;
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public Builder setStar1(int value) {
        bitField0_ |= 0x00000002;
        star1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public Builder clearStar1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        star1_ = 0;
        onChanged();
        return this;
      }

      private int star2_ ;
      /**
       * <code>optional uint32 star2 = 3;</code>
       */
      public boolean hasStar2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 star2 = 3;</code>
       */
      public int getStar2() {
        return star2_;
      }
      /**
       * <code>optional uint32 star2 = 3;</code>
       */
      public Builder setStar2(int value) {
        bitField0_ |= 0x00000004;
        star2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star2 = 3;</code>
       */
      public Builder clearStar2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        star2_ = 0;
        onChanged();
        return this;
      }

      private int star3_ ;
      /**
       * <code>optional uint32 star3 = 4;</code>
       */
      public boolean hasStar3() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 star3 = 4;</code>
       */
      public int getStar3() {
        return star3_;
      }
      /**
       * <code>optional uint32 star3 = 4;</code>
       */
      public Builder setStar3(int value) {
        bitField0_ |= 0x00000008;
        star3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star3 = 4;</code>
       */
      public Builder clearStar3() {
        bitField0_ = (bitField0_ & ~0x00000008);
        star3_ = 0;
        onChanged();
        return this;
      }

      private int star4_ ;
      /**
       * <code>optional uint32 star4 = 5;</code>
       */
      public boolean hasStar4() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 star4 = 5;</code>
       */
      public int getStar4() {
        return star4_;
      }
      /**
       * <code>optional uint32 star4 = 5;</code>
       */
      public Builder setStar4(int value) {
        bitField0_ |= 0x00000010;
        star4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star4 = 5;</code>
       */
      public Builder clearStar4() {
        bitField0_ = (bitField0_ & ~0x00000010);
        star4_ = 0;
        onChanged();
        return this;
      }

      private int star5_ ;
      /**
       * <code>optional uint32 star5 = 6;</code>
       */
      public boolean hasStar5() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 star5 = 6;</code>
       */
      public int getStar5() {
        return star5_;
      }
      /**
       * <code>optional uint32 star5 = 6;</code>
       */
      public Builder setStar5(int value) {
        bitField0_ |= 0x00000020;
        star5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star5 = 6;</code>
       */
      public Builder clearStar5() {
        bitField0_ = (bitField0_ & ~0x00000020);
        star5_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:biyunLevel)
    }

    static {
      defaultInstance = new biyunLevel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:biyunLevel)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_biyunLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_biyunLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020biyunLevel.proto\"f\n\nbiyunLevel\022\r\n\005leve" +
      "l\030\001 \001(\r\022\r\n\005star1\030\002 \001(\r\022\r\n\005star2\030\003 \001(\r\022\r\n" +
      "\005star3\030\004 \001(\r\022\r\n\005star4\030\005 \001(\r\022\r\n\005star5\030\006 \001" +
      "(\rB\021\n\017wang.gnim.excel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_biyunLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_biyunLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_biyunLevel_descriptor,
        new java.lang.String[] { "Level", "Star1", "Star2", "Star3", "Star4", "Star5", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
