// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BiyunLevel.proto

package wang.gnim.excel;

public final class BiyunLevel {
  private BiyunLevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Sheet1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sheet1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional uint32 level = 1;</code>
     */
    int getLevel();

    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    boolean hasStar1();
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    int getStar1();
  }
  /**
   * Protobuf type {@code Sheet1}
   */
  public static final class Sheet1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Sheet1)
      Sheet1OrBuilder {
    // Use Sheet1.newBuilder() to construct.
    private Sheet1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Sheet1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Sheet1 defaultInstance;
    public static Sheet1 getDefaultInstance() {
      return defaultInstance;
    }

    public Sheet1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Sheet1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              star1_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wang.gnim.excel.BiyunLevel.internal_static_Sheet1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wang.gnim.excel.BiyunLevel.internal_static_Sheet1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wang.gnim.excel.BiyunLevel.Sheet1.class, wang.gnim.excel.BiyunLevel.Sheet1.Builder.class);
    }

    public static com.google.protobuf.Parser<Sheet1> PARSER =
        new com.google.protobuf.AbstractParser<Sheet1>() {
      public Sheet1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sheet1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Sheet1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>optional uint32 level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int STAR1_FIELD_NUMBER = 2;
    private int star1_;
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    public boolean hasStar1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 star1 = 2;</code>
     */
    public int getStar1() {
      return star1_;
    }

    private void initFields() {
      level_ = 0;
      star1_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, star1_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, star1_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.BiyunLevel.Sheet1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wang.gnim.excel.BiyunLevel.Sheet1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sheet1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sheet1)
        wang.gnim.excel.BiyunLevel.Sheet1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wang.gnim.excel.BiyunLevel.internal_static_Sheet1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wang.gnim.excel.BiyunLevel.internal_static_Sheet1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wang.gnim.excel.BiyunLevel.Sheet1.class, wang.gnim.excel.BiyunLevel.Sheet1.Builder.class);
      }

      // Construct using wang.gnim.excel.BiyunLevel.Sheet1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        star1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wang.gnim.excel.BiyunLevel.internal_static_Sheet1_descriptor;
      }

      public wang.gnim.excel.BiyunLevel.Sheet1 getDefaultInstanceForType() {
        return wang.gnim.excel.BiyunLevel.Sheet1.getDefaultInstance();
      }

      public wang.gnim.excel.BiyunLevel.Sheet1 build() {
        wang.gnim.excel.BiyunLevel.Sheet1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wang.gnim.excel.BiyunLevel.Sheet1 buildPartial() {
        wang.gnim.excel.BiyunLevel.Sheet1 result = new wang.gnim.excel.BiyunLevel.Sheet1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.star1_ = star1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wang.gnim.excel.BiyunLevel.Sheet1) {
          return mergeFrom((wang.gnim.excel.BiyunLevel.Sheet1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wang.gnim.excel.BiyunLevel.Sheet1 other) {
        if (other == wang.gnim.excel.BiyunLevel.Sheet1.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasStar1()) {
          setStar1(other.getStar1());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wang.gnim.excel.BiyunLevel.Sheet1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wang.gnim.excel.BiyunLevel.Sheet1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int level_ ;
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      private int star1_ ;
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public boolean hasStar1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public int getStar1() {
        return star1_;
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public Builder setStar1(int value) {
        bitField0_ |= 0x00000002;
        star1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 star1 = 2;</code>
       */
      public Builder clearStar1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        star1_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Sheet1)
    }

    static {
      defaultInstance = new Sheet1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Sheet1)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sheet1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sheet1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BiyunLevel.proto\"&\n\006Sheet1\022\r\n\005level\030\001 " +
      "\001(\r\022\r\n\005star1\030\002 \001(\rB\021\n\017wang.gnim.excel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Sheet1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sheet1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Sheet1_descriptor,
        new java.lang.String[] { "Level", "Star1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
