// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package wang.gnim.excel;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExcelConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExcelConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    java.util.List<wang.gnim.excel.BiyunLevel.Sheet1> 
        getSheet1SList();
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    wang.gnim.excel.BiyunLevel.Sheet1 getSheet1S(int index);
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    int getSheet1SCount();
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    java.util.List<? extends wang.gnim.excel.BiyunLevel.Sheet1OrBuilder> 
        getSheet1SOrBuilderList();
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    wang.gnim.excel.BiyunLevel.Sheet1OrBuilder getSheet1SOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExcelConfig}
   */
  public static final class ExcelConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ExcelConfig)
      ExcelConfigOrBuilder {
    // Use ExcelConfig.newBuilder() to construct.
    private ExcelConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExcelConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExcelConfig defaultInstance;
    public static ExcelConfig getDefaultInstance() {
      return defaultInstance;
    }

    public ExcelConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExcelConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sheet1S_ = new java.util.ArrayList<wang.gnim.excel.BiyunLevel.Sheet1>();
                mutable_bitField0_ |= 0x00000001;
              }
              sheet1S_.add(input.readMessage(wang.gnim.excel.BiyunLevel.Sheet1.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sheet1S_ = java.util.Collections.unmodifiableList(sheet1S_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wang.gnim.excel.Config.internal_static_ExcelConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wang.gnim.excel.Config.ExcelConfig.class, wang.gnim.excel.Config.ExcelConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<ExcelConfig> PARSER =
        new com.google.protobuf.AbstractParser<ExcelConfig>() {
      public ExcelConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExcelConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExcelConfig> getParserForType() {
      return PARSER;
    }

    public static final int SHEET1S_FIELD_NUMBER = 1;
    private java.util.List<wang.gnim.excel.BiyunLevel.Sheet1> sheet1S_;
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    public java.util.List<wang.gnim.excel.BiyunLevel.Sheet1> getSheet1SList() {
      return sheet1S_;
    }
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    public java.util.List<? extends wang.gnim.excel.BiyunLevel.Sheet1OrBuilder> 
        getSheet1SOrBuilderList() {
      return sheet1S_;
    }
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    public int getSheet1SCount() {
      return sheet1S_.size();
    }
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    public wang.gnim.excel.BiyunLevel.Sheet1 getSheet1S(int index) {
      return sheet1S_.get(index);
    }
    /**
     * <code>repeated .Sheet1 Sheet1s = 1;</code>
     */
    public wang.gnim.excel.BiyunLevel.Sheet1OrBuilder getSheet1SOrBuilder(
        int index) {
      return sheet1S_.get(index);
    }

    private void initFields() {
      sheet1S_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sheet1S_.size(); i++) {
        output.writeMessage(1, sheet1S_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sheet1S_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sheet1S_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wang.gnim.excel.Config.ExcelConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExcelConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExcelConfig)
        wang.gnim.excel.Config.ExcelConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wang.gnim.excel.Config.ExcelConfig.class, wang.gnim.excel.Config.ExcelConfig.Builder.class);
      }

      // Construct using wang.gnim.excel.Config.ExcelConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSheet1SFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sheet1SBuilder_ == null) {
          sheet1S_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sheet1SBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
      }

      public wang.gnim.excel.Config.ExcelConfig getDefaultInstanceForType() {
        return wang.gnim.excel.Config.ExcelConfig.getDefaultInstance();
      }

      public wang.gnim.excel.Config.ExcelConfig build() {
        wang.gnim.excel.Config.ExcelConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wang.gnim.excel.Config.ExcelConfig buildPartial() {
        wang.gnim.excel.Config.ExcelConfig result = new wang.gnim.excel.Config.ExcelConfig(this);
        int from_bitField0_ = bitField0_;
        if (sheet1SBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sheet1S_ = java.util.Collections.unmodifiableList(sheet1S_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sheet1S_ = sheet1S_;
        } else {
          result.sheet1S_ = sheet1SBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wang.gnim.excel.Config.ExcelConfig) {
          return mergeFrom((wang.gnim.excel.Config.ExcelConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wang.gnim.excel.Config.ExcelConfig other) {
        if (other == wang.gnim.excel.Config.ExcelConfig.getDefaultInstance()) return this;
        if (sheet1SBuilder_ == null) {
          if (!other.sheet1S_.isEmpty()) {
            if (sheet1S_.isEmpty()) {
              sheet1S_ = other.sheet1S_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSheet1SIsMutable();
              sheet1S_.addAll(other.sheet1S_);
            }
            onChanged();
          }
        } else {
          if (!other.sheet1S_.isEmpty()) {
            if (sheet1SBuilder_.isEmpty()) {
              sheet1SBuilder_.dispose();
              sheet1SBuilder_ = null;
              sheet1S_ = other.sheet1S_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sheet1SBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSheet1SFieldBuilder() : null;
            } else {
              sheet1SBuilder_.addAllMessages(other.sheet1S_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wang.gnim.excel.Config.ExcelConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wang.gnim.excel.Config.ExcelConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<wang.gnim.excel.BiyunLevel.Sheet1> sheet1S_ =
        java.util.Collections.emptyList();
      private void ensureSheet1SIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sheet1S_ = new java.util.ArrayList<wang.gnim.excel.BiyunLevel.Sheet1>(sheet1S_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          wang.gnim.excel.BiyunLevel.Sheet1, wang.gnim.excel.BiyunLevel.Sheet1.Builder, wang.gnim.excel.BiyunLevel.Sheet1OrBuilder> sheet1SBuilder_;

      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public java.util.List<wang.gnim.excel.BiyunLevel.Sheet1> getSheet1SList() {
        if (sheet1SBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sheet1S_);
        } else {
          return sheet1SBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public int getSheet1SCount() {
        if (sheet1SBuilder_ == null) {
          return sheet1S_.size();
        } else {
          return sheet1SBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.Sheet1 getSheet1S(int index) {
        if (sheet1SBuilder_ == null) {
          return sheet1S_.get(index);
        } else {
          return sheet1SBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder setSheet1S(
          int index, wang.gnim.excel.BiyunLevel.Sheet1 value) {
        if (sheet1SBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSheet1SIsMutable();
          sheet1S_.set(index, value);
          onChanged();
        } else {
          sheet1SBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder setSheet1S(
          int index, wang.gnim.excel.BiyunLevel.Sheet1.Builder builderForValue) {
        if (sheet1SBuilder_ == null) {
          ensureSheet1SIsMutable();
          sheet1S_.set(index, builderForValue.build());
          onChanged();
        } else {
          sheet1SBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder addSheet1S(wang.gnim.excel.BiyunLevel.Sheet1 value) {
        if (sheet1SBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSheet1SIsMutable();
          sheet1S_.add(value);
          onChanged();
        } else {
          sheet1SBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder addSheet1S(
          int index, wang.gnim.excel.BiyunLevel.Sheet1 value) {
        if (sheet1SBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSheet1SIsMutable();
          sheet1S_.add(index, value);
          onChanged();
        } else {
          sheet1SBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder addSheet1S(
          wang.gnim.excel.BiyunLevel.Sheet1.Builder builderForValue) {
        if (sheet1SBuilder_ == null) {
          ensureSheet1SIsMutable();
          sheet1S_.add(builderForValue.build());
          onChanged();
        } else {
          sheet1SBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder addSheet1S(
          int index, wang.gnim.excel.BiyunLevel.Sheet1.Builder builderForValue) {
        if (sheet1SBuilder_ == null) {
          ensureSheet1SIsMutable();
          sheet1S_.add(index, builderForValue.build());
          onChanged();
        } else {
          sheet1SBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder addAllSheet1S(
          java.lang.Iterable<? extends wang.gnim.excel.BiyunLevel.Sheet1> values) {
        if (sheet1SBuilder_ == null) {
          ensureSheet1SIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sheet1S_);
          onChanged();
        } else {
          sheet1SBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder clearSheet1S() {
        if (sheet1SBuilder_ == null) {
          sheet1S_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sheet1SBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public Builder removeSheet1S(int index) {
        if (sheet1SBuilder_ == null) {
          ensureSheet1SIsMutable();
          sheet1S_.remove(index);
          onChanged();
        } else {
          sheet1SBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.Sheet1.Builder getSheet1SBuilder(
          int index) {
        return getSheet1SFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.Sheet1OrBuilder getSheet1SOrBuilder(
          int index) {
        if (sheet1SBuilder_ == null) {
          return sheet1S_.get(index);  } else {
          return sheet1SBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public java.util.List<? extends wang.gnim.excel.BiyunLevel.Sheet1OrBuilder> 
           getSheet1SOrBuilderList() {
        if (sheet1SBuilder_ != null) {
          return sheet1SBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sheet1S_);
        }
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.Sheet1.Builder addSheet1SBuilder() {
        return getSheet1SFieldBuilder().addBuilder(
            wang.gnim.excel.BiyunLevel.Sheet1.getDefaultInstance());
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.Sheet1.Builder addSheet1SBuilder(
          int index) {
        return getSheet1SFieldBuilder().addBuilder(
            index, wang.gnim.excel.BiyunLevel.Sheet1.getDefaultInstance());
      }
      /**
       * <code>repeated .Sheet1 Sheet1s = 1;</code>
       */
      public java.util.List<wang.gnim.excel.BiyunLevel.Sheet1.Builder> 
           getSheet1SBuilderList() {
        return getSheet1SFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          wang.gnim.excel.BiyunLevel.Sheet1, wang.gnim.excel.BiyunLevel.Sheet1.Builder, wang.gnim.excel.BiyunLevel.Sheet1OrBuilder> 
          getSheet1SFieldBuilder() {
        if (sheet1SBuilder_ == null) {
          sheet1SBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              wang.gnim.excel.BiyunLevel.Sheet1, wang.gnim.excel.BiyunLevel.Sheet1.Builder, wang.gnim.excel.BiyunLevel.Sheet1OrBuilder>(
                  sheet1S_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sheet1S_ = null;
        }
        return sheet1SBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ExcelConfig)
    }

    static {
      defaultInstance = new ExcelConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExcelConfig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExcelConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExcelConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\032\020BiyunLevel.proto\"\'\n\013Exce" +
      "lConfig\022\030\n\007Sheet1s\030\001 \003(\0132\007.Sheet1B\021\n\017wan" +
      "g.gnim.excel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          wang.gnim.excel.BiyunLevel.getDescriptor(),
        }, assigner);
    internal_static_ExcelConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExcelConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ExcelConfig_descriptor,
        new java.lang.String[] { "Sheet1S", });
    wang.gnim.excel.BiyunLevel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
