// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package wang.gnim.excel;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExcelConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExcelConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel> 
        getBiyunLevelsList();
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    wang.gnim.excel.BiyunLevel.biyunLevel getBiyunLevels(int index);
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    int getBiyunLevelsCount();
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    java.util.List<? extends wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder> 
        getBiyunLevelsOrBuilderList();
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder getBiyunLevelsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExcelConfig}
   */
  public static final class ExcelConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ExcelConfig)
      ExcelConfigOrBuilder {
    // Use ExcelConfig.newBuilder() to construct.
    private ExcelConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExcelConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExcelConfig defaultInstance;
    public static ExcelConfig getDefaultInstance() {
      return defaultInstance;
    }

    public ExcelConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExcelConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                biyunLevels_ = new java.util.ArrayList<wang.gnim.excel.BiyunLevel.biyunLevel>();
                mutable_bitField0_ |= 0x00000001;
              }
              biyunLevels_.add(input.readMessage(wang.gnim.excel.BiyunLevel.biyunLevel.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          biyunLevels_ = java.util.Collections.unmodifiableList(biyunLevels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wang.gnim.excel.Config.internal_static_ExcelConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wang.gnim.excel.Config.ExcelConfig.class, wang.gnim.excel.Config.ExcelConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<ExcelConfig> PARSER =
        new com.google.protobuf.AbstractParser<ExcelConfig>() {
      public ExcelConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExcelConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExcelConfig> getParserForType() {
      return PARSER;
    }

    public static final int BIYUNLEVELS_FIELD_NUMBER = 1;
    private java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel> biyunLevels_;
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    public java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel> getBiyunLevelsList() {
      return biyunLevels_;
    }
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    public java.util.List<? extends wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder> 
        getBiyunLevelsOrBuilderList() {
      return biyunLevels_;
    }
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    public int getBiyunLevelsCount() {
      return biyunLevels_.size();
    }
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    public wang.gnim.excel.BiyunLevel.biyunLevel getBiyunLevels(int index) {
      return biyunLevels_.get(index);
    }
    /**
     * <code>repeated .biyunLevel biyunLevels = 1;</code>
     */
    public wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder getBiyunLevelsOrBuilder(
        int index) {
      return biyunLevels_.get(index);
    }

    private void initFields() {
      biyunLevels_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < biyunLevels_.size(); i++) {
        output.writeMessage(1, biyunLevels_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < biyunLevels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, biyunLevels_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static wang.gnim.excel.Config.ExcelConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wang.gnim.excel.Config.ExcelConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExcelConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExcelConfig)
        wang.gnim.excel.Config.ExcelConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wang.gnim.excel.Config.ExcelConfig.class, wang.gnim.excel.Config.ExcelConfig.Builder.class);
      }

      // Construct using wang.gnim.excel.Config.ExcelConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBiyunLevelsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (biyunLevelsBuilder_ == null) {
          biyunLevels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          biyunLevelsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wang.gnim.excel.Config.internal_static_ExcelConfig_descriptor;
      }

      public wang.gnim.excel.Config.ExcelConfig getDefaultInstanceForType() {
        return wang.gnim.excel.Config.ExcelConfig.getDefaultInstance();
      }

      public wang.gnim.excel.Config.ExcelConfig build() {
        wang.gnim.excel.Config.ExcelConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wang.gnim.excel.Config.ExcelConfig buildPartial() {
        wang.gnim.excel.Config.ExcelConfig result = new wang.gnim.excel.Config.ExcelConfig(this);
        int from_bitField0_ = bitField0_;
        if (biyunLevelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            biyunLevels_ = java.util.Collections.unmodifiableList(biyunLevels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.biyunLevels_ = biyunLevels_;
        } else {
          result.biyunLevels_ = biyunLevelsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wang.gnim.excel.Config.ExcelConfig) {
          return mergeFrom((wang.gnim.excel.Config.ExcelConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wang.gnim.excel.Config.ExcelConfig other) {
        if (other == wang.gnim.excel.Config.ExcelConfig.getDefaultInstance()) return this;
        if (biyunLevelsBuilder_ == null) {
          if (!other.biyunLevels_.isEmpty()) {
            if (biyunLevels_.isEmpty()) {
              biyunLevels_ = other.biyunLevels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBiyunLevelsIsMutable();
              biyunLevels_.addAll(other.biyunLevels_);
            }
            onChanged();
          }
        } else {
          if (!other.biyunLevels_.isEmpty()) {
            if (biyunLevelsBuilder_.isEmpty()) {
              biyunLevelsBuilder_.dispose();
              biyunLevelsBuilder_ = null;
              biyunLevels_ = other.biyunLevels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              biyunLevelsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBiyunLevelsFieldBuilder() : null;
            } else {
              biyunLevelsBuilder_.addAllMessages(other.biyunLevels_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wang.gnim.excel.Config.ExcelConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wang.gnim.excel.Config.ExcelConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel> biyunLevels_ =
        java.util.Collections.emptyList();
      private void ensureBiyunLevelsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          biyunLevels_ = new java.util.ArrayList<wang.gnim.excel.BiyunLevel.biyunLevel>(biyunLevels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          wang.gnim.excel.BiyunLevel.biyunLevel, wang.gnim.excel.BiyunLevel.biyunLevel.Builder, wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder> biyunLevelsBuilder_;

      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel> getBiyunLevelsList() {
        if (biyunLevelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(biyunLevels_);
        } else {
          return biyunLevelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public int getBiyunLevelsCount() {
        if (biyunLevelsBuilder_ == null) {
          return biyunLevels_.size();
        } else {
          return biyunLevelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.biyunLevel getBiyunLevels(int index) {
        if (biyunLevelsBuilder_ == null) {
          return biyunLevels_.get(index);
        } else {
          return biyunLevelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder setBiyunLevels(
          int index, wang.gnim.excel.BiyunLevel.biyunLevel value) {
        if (biyunLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBiyunLevelsIsMutable();
          biyunLevels_.set(index, value);
          onChanged();
        } else {
          biyunLevelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder setBiyunLevels(
          int index, wang.gnim.excel.BiyunLevel.biyunLevel.Builder builderForValue) {
        if (biyunLevelsBuilder_ == null) {
          ensureBiyunLevelsIsMutable();
          biyunLevels_.set(index, builderForValue.build());
          onChanged();
        } else {
          biyunLevelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder addBiyunLevels(wang.gnim.excel.BiyunLevel.biyunLevel value) {
        if (biyunLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBiyunLevelsIsMutable();
          biyunLevels_.add(value);
          onChanged();
        } else {
          biyunLevelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder addBiyunLevels(
          int index, wang.gnim.excel.BiyunLevel.biyunLevel value) {
        if (biyunLevelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBiyunLevelsIsMutable();
          biyunLevels_.add(index, value);
          onChanged();
        } else {
          biyunLevelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder addBiyunLevels(
          wang.gnim.excel.BiyunLevel.biyunLevel.Builder builderForValue) {
        if (biyunLevelsBuilder_ == null) {
          ensureBiyunLevelsIsMutable();
          biyunLevels_.add(builderForValue.build());
          onChanged();
        } else {
          biyunLevelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder addBiyunLevels(
          int index, wang.gnim.excel.BiyunLevel.biyunLevel.Builder builderForValue) {
        if (biyunLevelsBuilder_ == null) {
          ensureBiyunLevelsIsMutable();
          biyunLevels_.add(index, builderForValue.build());
          onChanged();
        } else {
          biyunLevelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder addAllBiyunLevels(
          java.lang.Iterable<? extends wang.gnim.excel.BiyunLevel.biyunLevel> values) {
        if (biyunLevelsBuilder_ == null) {
          ensureBiyunLevelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, biyunLevels_);
          onChanged();
        } else {
          biyunLevelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder clearBiyunLevels() {
        if (biyunLevelsBuilder_ == null) {
          biyunLevels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          biyunLevelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public Builder removeBiyunLevels(int index) {
        if (biyunLevelsBuilder_ == null) {
          ensureBiyunLevelsIsMutable();
          biyunLevels_.remove(index);
          onChanged();
        } else {
          biyunLevelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.biyunLevel.Builder getBiyunLevelsBuilder(
          int index) {
        return getBiyunLevelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder getBiyunLevelsOrBuilder(
          int index) {
        if (biyunLevelsBuilder_ == null) {
          return biyunLevels_.get(index);  } else {
          return biyunLevelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public java.util.List<? extends wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder> 
           getBiyunLevelsOrBuilderList() {
        if (biyunLevelsBuilder_ != null) {
          return biyunLevelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(biyunLevels_);
        }
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.biyunLevel.Builder addBiyunLevelsBuilder() {
        return getBiyunLevelsFieldBuilder().addBuilder(
            wang.gnim.excel.BiyunLevel.biyunLevel.getDefaultInstance());
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public wang.gnim.excel.BiyunLevel.biyunLevel.Builder addBiyunLevelsBuilder(
          int index) {
        return getBiyunLevelsFieldBuilder().addBuilder(
            index, wang.gnim.excel.BiyunLevel.biyunLevel.getDefaultInstance());
      }
      /**
       * <code>repeated .biyunLevel biyunLevels = 1;</code>
       */
      public java.util.List<wang.gnim.excel.BiyunLevel.biyunLevel.Builder> 
           getBiyunLevelsBuilderList() {
        return getBiyunLevelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          wang.gnim.excel.BiyunLevel.biyunLevel, wang.gnim.excel.BiyunLevel.biyunLevel.Builder, wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder> 
          getBiyunLevelsFieldBuilder() {
        if (biyunLevelsBuilder_ == null) {
          biyunLevelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              wang.gnim.excel.BiyunLevel.biyunLevel, wang.gnim.excel.BiyunLevel.biyunLevel.Builder, wang.gnim.excel.BiyunLevel.biyunLevelOrBuilder>(
                  biyunLevels_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          biyunLevels_ = null;
        }
        return biyunLevelsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ExcelConfig)
    }

    static {
      defaultInstance = new ExcelConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExcelConfig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExcelConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExcelConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\032\020biyunLevel.proto\"/\n\013Exce" +
      "lConfig\022 \n\013biyunLevels\030\001 \003(\0132\013.biyunLeve" +
      "lB\021\n\017wang.gnim.excel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          wang.gnim.excel.BiyunLevel.getDescriptor(),
        }, assigner);
    internal_static_ExcelConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExcelConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ExcelConfig_descriptor,
        new java.lang.String[] { "BiyunLevels", });
    wang.gnim.excel.BiyunLevel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
